events {}

http {
    upstream auth_service {
        server auth-service:4001;
    }

    upstream core_service {
        server core-service:4002;
    }

    server {
        listen 8080;

        location /auth/ {
            proxy_pass http://auth_service/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /vehicles/ {
            proxy_pass http://core_service/vehicles/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /service-logs/ {
            proxy_pass http://core_service/service-logs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/auth {
            proxy_pass http://auth_service/health;
        }

        location /health/core {
            proxy_pass http://core_service/health;
        }
    }
}
