apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: car-tracker-production

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: car-tracker-gateway
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.car-tracker.example.com
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: core-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: auth-service:local
    newName: registry.gitlab.yourcompany.example.com/your-group/car-service-tracker/auth-service
    newTag: production-latest
  - name: core-service:local
    newName: registry.gitlab.yourcompany.example.com/your-group/car-service-tracker/core-service
    newTag: production-latest
